HEURISTICS_DICT = {
    "mouse20_notail": {
        "Bad_Tracking": {
            "high": [
                "abs_vel_norm_Snout_3",
                "abs_vel_norm_Tail_base__3",
                "abs_vel_norm_SpineM_3",
                "abs_vel_std_norm_Snout_3",
                "abs_vel_std_norm_Tail_base__3",
                "abs_vel_std_norm_SpineM_3",
            ],
            "low": [],
        },
        "Rear": {
            "high": [
                "rel_vel_z_Snout_31",
                "rel_vel_z_EarR_31",
                "rel_vel_z_EarL_31",
                "abs_vel_z_Snout_31",
                "abs_vel_z_Snout_91",
                "abs_vel_z_SpineF_31",
                "abs_vel_z_SpineF_91",
                "ego_euc_Snout_z",
                "ego_euc_EarR_z",
                "ego_euc_EarL_z",
            ],
            "low": [
                "abs_vel_norm_Tail_base__31",
                "abs_vel_z_Tail_base__31",
                "abs_vel_norm_Tail_base__91",
                "abs_vel_z_Tail_base__91",
                "abs_vel_std_norm_Tail_base__3",
                "abs_vel_std_x_Tail_base__3",
                "abs_vel_std_y_Tail_base__3",
                "abs_vel_std_z_Tail_base__3",
                "abs_vel_std_norm_Tail_base__31",
                "abs_vel_std_x_Tail_base__31",
                "abs_vel_std_y_Tail_base__31",
                "abs_vel_std_z_Tail_base__31",
                "abs_vel_std_norm_Tail_base__91",
                "abs_vel_std_x_Tail_base__91",
                "abs_vel_std_y_Tail_base__91",
                "abs_vel_std_z_Tail_base__91",
            ],
        },
        "Walk": {
            "high": [
                "rel_vel_std_x_Wrist_L_91",
                "rel_vel_std_y_Wrist_L_91",
                "rel_vel_std_norm_Wrist_L_91",
                "rel_vel_std_x_Wrist_R_91",
                "rel_vel_std_y_Wrist_R_91",
                "rel_vel_std_norm_Wrist_R_91",
                "rel_vel_std_x_Ankel_L_91",
                "rel_vel_std_y_Ankel_L_91",
                "rel_vel_std_norm_Ankel_L_91",
                "rel_vel_std_x_Ankel_R_91",
                "rel_vel_std_y_Ankel_R_91",
                "rel_vel_std_norm_Ankel_R_91",
                "avel_std_xz_7_4_16_91",
                "avel_std_xz_7_4_16_31",
                "avel_std_xz_7_3_10_91",
                "avel_std_xz_7_3_10_31",
                "avel_std_xz_10_4_13_91",
                "avel_std_xz_10_4_13_31",
            ],
            "low": [
                "avel_std_yz_7_4_16_91",
                "avel_std_yz_7_4_16_31",
                "avel_std_yz_7_3_10_91",
                "avel_std_yz_7_3_10_31",
                "avel_std_yz_10_4_13_91",
                "avel_std_yz_10_4_13_31",
                "abs_vel_z_Tail_base__3",
                "abs_vel_z_Tail_base__31",
                "abs_vel_z_Tail_base__91",
                "abs_vel_z_SpineM_3",
                "abs_vel_z_SpineM_31",
                "abs_vel_z_SpineM_91",
                "abs_vel_z_SpineF_3",
                "abs_vel_z_SpineF_31",
                "abs_vel_z_SpineF_91",
            ],
        },
        "Still": {
            "high": ["ang_xz_3_4_5", "ang_xy_3_4_5", "ang_xz_0_3_4", "ang_xy_0_3_4"],
            "low": [
                "abs_vel_norm_Snout_91",
                "abs_vel_norm_Tail_base__91",
                "abs_vel_norm_SpineM_91",
                "abs_vel_std_norm_Snout_91",
                "abs_vel_std_norm_Tail_base__91",
                "abs_vel_std_norm_SpineM_91",
                "rel_vel_std_x_Wrist_L_91",
                "rel_vel_std_y_Wrist_L_91",
                "rel_vel_std_norm_Wrist_L_91",
                "rel_vel_std_x_Wrist_R_91",
                "rel_vel_std_y_Wrist_R_91",
                "rel_vel_std_norm_Wrist_R_91",
                "rel_vel_std_x_Ankel_L_91",
                "rel_vel_std_y_Ankel_L_91",
                "rel_vel_std_norm_Ankel_L_91",
                "rel_vel_std_x_Ankel_R_91",
                "rel_vel_std_y_Ankel_R_91",
                "rel_vel_std_norm_Ankel_R_91",
            ],
        },
        "Hunched": {
            "high": [],
            "low": [
                "abs_vel_norm_Snout_91",
                "abs_vel_norm_Tail_base__91",
                "abs_vel_norm_SpineM_91",
                "abs_vel_norm_Snout_31",
                "abs_vel_norm_Tail_base__31",
                "abs_vel_norm_SpineM_31",
                "abs_vel_norm_Snout_3",
                "abs_vel_norm_Tail_base__3",
                "abs_vel_norm_SpineM_3",
                "abs_vel_std_norm_Snout_91",
                "abs_vel_std_norm_Tail_base__91",
                "abs_vel_std_norm_SpineM_91",
                "abs_vel_std_norm_Snout_31",
                "abs_vel_std_norm_Tail_base__31",
                "abs_vel_std_norm_SpineM_31",
                "abs_vel_std_norm_Snout_3",
                "abs_vel_std_norm_Tail_base__3",
                "abs_vel_std_norm_SpineM_3",
                "rel_vel_std_x_Wrist_L_91",
                "rel_vel_std_y_Wrist_L_91",
                "rel_vel_std_norm_Wrist_L_91",
                "rel_vel_std_x_Wrist_R_91",
                "rel_vel_std_y_Wrist_R_91",
                "rel_vel_std_norm_Wrist_R_91",
                "rel_vel_std_x_Ankel_L_91",
                "rel_vel_std_y_Ankel_L_91",
                "rel_vel_std_norm_Ankel_L_91",
                "rel_vel_std_x_Ankel_R_91",
                "rel_vel_std_y_Ankel_R_91",
                "rel_vel_std_norm_Ankel_R_91",
                "ang_xz_3_4_5",
                "ang_xy_3_4_5",
            ],
        },
        "Groom": {
            "high": [
                "rel_vel_std_x_Wrist_R_91",
                "rel_vel_std_y_Wrist_R_91",
                "rel_vel_std_z_Wrist_R_91",
                "rel_vel_std_norm_Wrist_R_91",
                "rel_vel_std_x_Wrist_R_31",
                "rel_vel_std_y_Wrist_R_31",
                "rel_vel_std_z_Wrist_R_31",
                "rel_vel_std_norm_Wrist_R_31",
            ],
            "low": [
                "abs_vel_norm_Tail_base__91",
                "abs_vel_norm_SpineM_91",
                "abs_vel_norm_Tail_base__31",
                "abs_vel_norm_SpineM_31",
                "abs_vel_norm_Tail_base__3",
                "abs_vel_norm_SpineM_3",
                "ang_xy_0_3_7",
                "ang_xz_0_3_7",
                "ang_yz_0_3_7",
                "ang_xy_0_3_10",
                "ang_xz_0_3_10",
                "ang_yz_0_3_10",
                "ego_euc_Tail_base__z",
            ],
        },
    }
}
